print("██████╗ ██╗  ██╗██╗███████╗██╗  ██╗██████╗  ██████╗ ██╗  ██╗")
print("██╔══██╗██║  ██║██║██╔════╝██║  ██║██╔══██╗██╔═══██╗╚██╗██╔╝")
print("██████╔╝███████║██║███████╗███████║██████╔╝██║   ██║ ╚███╔╝")
print("██╔═══╝ ██╔══██║██║╚════██║██╔══██║██╔══██╗██║   ██║ ██╔██╗")
print("██║     ██║  ██║██║███████║██║  ██║██████╔╝╚██████╔╝██╔╝ ██")
print("╚═╝     ╚═╝  ╚═╝╚═╝╚══════╝╚═╝  ╚═╝╚═════╝  ╚═════╝ ╚═╝  ╚═╝")

#Please change the version and edit date when changes are made cause it looks offical :)
print("Version 0")
print("Last edit: 9/20/19")
print("By DJCHICKEN4, Commi3, ???")
print("This is to be used for legal and educational purposes only. Any other use is not intended.")
